batch_nums_per_epoch: 120
feature_dims: 64
fix_len: 16
lr: 0.0001
max_step: 10000
model_name: ge2e
n_fft: 512
n_gpu: 1
n_speaker: 368
n_speaker_test: 30
n_threads: 6
hop_length: 128
num_classes_per_batch: 16
num_utt_per_class: 4
sample_rate: 16000
save_path: /home/fhq/save/ge2e
slides:
- 0
- 0
